In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('C:/Users/prati/Downloads/DatasetAssignment1.csv')
df.head()

C:\Users\prati\AppData\Local\Temp\ipykernel_11608\1977799454.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

,Movie Title,Release Date,Wikipedia URL,Genre,Director (1),Director (2),Cast (1),Cast (2),Cast (3),Cast (4),Cast (5),Budget,Revenue
0,10 Cloverfield Lane,2016-03-08,https://en.wikipedia.org/wiki/10_Cloverfield_Lane,Thriller,Dan Trachtenberg,NaN,Mary Elizabeth Winstead,John Goodman,John Gallagher,NaN,NaN,"$15,000,000.00","$108,300,000.00"
1,13 Hours: The Secret Soldiers of Benghazi,2016-01-15,https://en.wikipedia.org/wiki/13_Hours:_The_Se...,Action,Michael Bay,NaN,James Badge Dale,John Krasinski,Toby Stephens,Pablo Schreiber,Max Martini,"$45,000,000.00","$69,400,000.00"
2,2 Guns,2013-08-02,https://en.wikipedia.org/wiki/2_Guns,Action,Baltasar Kormákur,NaN,Mark Wahlberg,Denzel Washington,Paula Patton,Bill Paxton,Edward James Olmos,"$61,000,000.00","$131,900,000.00"
3,21 Jump Street,2012-03-16,https://en.wikipedia.org/wiki/21_Jump_Street_(...,Comedy,Phil Lord,Chris Miller,Jonah Hill,Channing Tatum,Ice Cube,Brie Larson,Rob Riggle,"$55,000,000.00","$201,500,000.00"
4,22 Jump Street,2014-06-04,https://en.wikipedia.org/wiki/22_Jump_Street,Action,Phil Lord,Chris Miller,Channing Tatum,Jonah Hill,Ice Cube,NaN,NaN,"$84,500,000.00","$331,300,000.00"

In [2]:
to_drop = ['Director (2)']

df.drop(to_drop, inplace=True, axis=1)

In [3]:
df.head()

,Movie Title,Release Date,Wikipedia URL,Genre,Director (1),Cast (1),Cast (2),Cast (3),Cast (4),Cast (5),Budget,Revenue
0,10 Cloverfield Lane,2016-03-08,https://en.wikipedia.org/wiki/10_Cloverfield_Lane,Thriller,Dan Trachtenberg,Mary Elizabeth Winstead,John Goodman,John Gallagher,NaN,NaN,"$15,000,000.00","$108,300,000.00"
1,13 Hours: The Secret Soldiers of Benghazi,2016-01-15,https://en.wikipedia.org/wiki/13_Hours:_The_Se...,Action,Michael Bay,James Badge Dale,John Krasinski,Toby Stephens,Pablo Schreiber,Max Martini,"$45,000,000.00","$69,400,000.00"
2,2 Guns,2013-08-02,https://en.wikipedia.org/wiki/2_Guns,Action,Baltasar Kormákur,Mark Wahlberg,Denzel Washington,Paula Patton,Bill Paxton,Edward James Olmos,"$61,000,000.00","$131,900,000.00"
3,21 Jump Street,2012-03-16,https://en.wikipedia.org/wiki/21_Jump_Street_(...,Comedy,Phil Lord,Jonah Hill,Channing Tatum,Ice Cube,Brie Larson,Rob Riggle,"$55,000,000.00","$201,500,000.00"
4,22 Jump Street,2014-06-04,https://en.wikipedia.org/wiki/22_Jump_Street,Action,Phil Lord,Channing Tatum,Jonah Hill,Ice Cube,NaN,NaN,"$84,500,000.00","$331,300,000.00"

In [4]:
df['Movie Title'].is_unique

True

In [5]:
df = df.set_index('Movie Title')
df.head()

,Release Date,Wikipedia URL,Genre,Director (1),Cast (1),Cast (2),Cast (3),Cast (4),Cast (5),Budget,Revenue
Movie Title,,,,,,,,,,,
10 Cloverfield Lane,2016-03-08,https://en.wikipedia.org/wiki/10_Cloverfield_Lane,Thriller,Dan Trachtenberg,Mary Elizabeth Winstead,John Goodman,John Gallagher,NaN,NaN,"$15,000,000.00","$108,300,000.00"
13 Hours: The Secret Soldiers of Benghazi,2016-01-15,https://en.wikipedia.org/wiki/13_Hours:_The_Se...,Action,Michael Bay,James Badge Dale,John Krasinski,Toby Stephens,Pablo Schreiber,Max Martini,"$45,000,000.00","$69,400,000.00"
2 Guns,2013-08-02,https://en.wikipedia.org/wiki/2_Guns,Action,Baltasar Kormákur,Mark Wahlberg,Denzel Washington,Paula Patton,Bill Paxton,Edward James Olmos,"$61,000,000.00","$131,900,000.00"
21 Jump Street,2012-03-16,https://en.wikipedia.org/wiki/21_Jump_Street_(...,Comedy,Phil Lord,Jonah Hill,Channing Tatum,Ice Cube,Brie Larson,Rob Riggle,"$55,000,000.00","$201,500,000.00"
22 Jump Street,2014-06-04,https://en.wikipedia.org/wiki/22_Jump_Street,Action,Phil Lord,Channing Tatum,Jonah Hill,Ice Cube,NaN,NaN,"$84,500,000.00","$331,300,000.00"

In [6]:
df.loc['22 Jump Street']

Release Date                                       2014-06-04
Wikipedia URL    https://en.wikipedia.org/wiki/22_Jump_Street
Genre                                                  Action
Director (1)                                        Phil Lord
Cast (1)                                       Channing Tatum
Cast (2)                                           Jonah Hill
Cast (3)                                             Ice Cube
Cast (4)                                                  NaN
Cast (5)                                                  NaN
Budget                                         $84,500,000.00
Revenue                                       $331,300,000.00
Name: 22 Jump Street, dtype: object

In [7]:
df.loc['22 Jump Street':, 'Budget '].head(10)

Movie Title
22 Jump Street             $84,500,000.00
300: Rise of an Empire    $110,000,000.00
42                         $40,000,000.00
71                          $8,100,000.00
90 Minutes in Heaven        $5,000,000.00
A Good Day to Die Hard     $92,000,000.00
A Haunted House             $2,500,000.00
A Haunted House 2           $4,000,000.00
A Long Way Down            $22,700,000.00
A Most Violent Year        $20,000,000.00
Name: Budget , dtype: object

In [9]:
df.columns

Index(['Release Date', 'Wikipedia URL', 'Genre', 'Director (1)', 'Cast (1)',
       'Cast (2)', 'Cast (3)', 'Cast (4)', 'Cast (5)', 'Budget ', 'Revenue'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 508 entries, 10 Cloverfield Lane to Zoolander 2
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Release Date   508 non-null    object
 1   Wikipedia URL  508 non-null    object
 2   Genre          508 non-null    object
 3   Director (1)   508 non-null    object
 4   Cast (1)       508 non-null    object
 5   Cast (2)       503 non-null    object
 6   Cast (3)       485 non-null    object
 7   Cast (4)       452 non-null    object
 8   Cast (5)       389 non-null    object
 9   Budget         508 non-null    object
 10  Revenue        508 non-null    object
dtypes: object(11)
memory usage: 63.8+ KB

In [13]:
df.loc[df.isna().any(axis="columns")]

,Release Date,Wikipedia URL,Genre,Director (1),Cast (1),Cast (2),Cast (3),Cast (4),Cast (5),Budget,Revenue
Movie Title,,,,,,,,,,,
10 Cloverfield Lane,2016-03-08,https://en.wikipedia.org/wiki/10_Cloverfield_Lane,Thriller,Dan Trachtenberg,Mary Elizabeth Winstead,John Goodman,John Gallagher,NaN,NaN,"$15,000,000.00","$108,300,000.00"
22 Jump Street,2014-06-04,https://en.wikipedia.org/wiki/22_Jump_Street,Action,Phil Lord,Channing Tatum,Jonah Hill,Ice Cube,NaN,NaN,"$84,500,000.00","$331,300,000.00"
71,2014-02-07,https://en.wikipedia.org/wiki/%252771_(film),Action,Yann Demange,Jack O'Connell,Richard Dormer,Sean Harris,Sam Reid,NaN,"$8,100,000.00","$2,900,000.00"
90 Minutes in Heaven,2015-09-11,https://en.wikipedia.org/wiki/90_Minutes_in_He...,Drama,Michael Polish,Hayden Christensen,Kate Bosworth,Dwight Yoakam,Michael W. Smith,NaN,"$5,000,000.00","$4,800,000.00"
A Long Way Down,2014-02-10,https://en.wikipedia.org/wiki/A_Long_Way_Down_...,Comedy,Pascal Chaumeil,Toni Collette,Pierce Brosnan,Aaron Paul,Imogen Poots,NaN,"$22,700,000.00","$7,100,000.00"
...,...,...,...,...,...,...,...,...,...,...,...
Victor Frankenstein,2015-11-25,https://en.wikipedia.org/wiki/Victor_Frankenst...,Horror,Paul McGuigan,Daniel Radcliffe,James McAvoy,Jessica Brown Findlay,Andrew Scott,NaN,"$40,000,000.00","$34,200,000.00"
War Dogs,2016-08-19,https://en.wikipedia.org/wiki/War_Dogs_(2016_f...,Crime,Todd Phillips,Jonah Hill,Miles Teller,Ana de Armas,J. B. Blanc,NaN,"$40,000,000.00","$42,700,000.00"
When the Game Stands Tall,2014-08-04,https://en.wikipedia.org/wiki/When_the_Game_St...,Religious,Thomas Carter,Jim Caviezel,Laura Dern,Michael Chiklis,Alexander Ludwig,NaN,"$15,000,000.00","$30,100,000.00"
Whiplash,2014-01-16,https://en.wikipedia.org/wiki/Whiplash_(2014_f...,Drama,Damien Chazelle,J. K. Simmons,Miles Teller,Paul Reiser,Melissa Benoist,NaN,"$3,300,000.00","$49,000,000.00"
Wild,2014-08-29,https://en.wikipedia.org/wiki/Wild_(2014_film),Drama,Jean-Marc Vallée,Reese Witherspoon,Gaby Hoffmann,Michiel Huisman,Charles Baker,NaN,"$15,000,000.00","$52,500,000.00"

In [15]:
df.to_csv("C:/Users/prati/Downloads/Assign1data_cleansed.csv", index=False)